import { getCosmosClient, DB_NAME } from '../client.js';
import type { ServiceCategory } from '../../schemas/service-category.js';
import type { Service } from '../../schemas/service.js';

const NOW = new Date().toISOString();
const SYSTEM = 'seed-script';

const CATEGORIES: ServiceCategory[] = [
  { id: 'ac-repair', name: 'AC Repair', heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/categories%2Fac-repair.jpg', sortOrder: 1, isActive: true, updatedBy: SYSTEM, createdAt: NOW, updatedAt: NOW },
  { id: 'deep-cleaning', name: 'Deep Cleaning', heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/categories%2Fdeep-cleaning.jpg', sortOrder: 2, isActive: true, updatedBy: SYSTEM, createdAt: NOW, updatedAt: NOW },
  { id: 'plumbing', name: 'Plumbing', heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/categories%2Fplumbing.jpg', sortOrder: 3, isActive: true, updatedBy: SYSTEM, createdAt: NOW, updatedAt: NOW },
  { id: 'electrical', name: 'Electrical', heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/categories%2Felectrical.jpg', sortOrder: 4, isActive: true, updatedBy: SYSTEM, createdAt: NOW, updatedAt: NOW },
  { id: 'pest-control', name: 'Pest Control', heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/categories%2Fpest-control.jpg', sortOrder: 5, isActive: true, updatedBy: SYSTEM, createdAt: NOW, updatedAt: NOW },
];

const SERVICES: Service[] = [
  // AC Repair
  {
    id: 'ac-deep-clean',
    categoryId: 'ac-repair',
    name: 'AC Deep Clean',
    shortDescription: 'Chemical wash, gas check, filter clean — fully covered at ₹599.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fac-deep-clean.jpg',
    basePrice: 59900,
    commissionBps: 2250,
    durationMinutes: 90,
    includes: ['Chemical wash of coils and filter', 'Gas pressure check', 'Full function test run', 'Drain pipe cleaning'],
    faq: [{ question: 'How often should I get this done?', answer: 'Every 3 months for optimal efficiency.' }, { question: 'Is gas refill included?', answer: 'No — gas refill is an add-on if pressure is low.' }],
    addOns: [{ id: 'gas-refill', name: 'Gas Refill', price: 149900, triggerCondition: 'if gas pressure is below recommended threshold' }],
    photoStages: [{ id: 'before-unit', label: 'AC unit before service', required: true }, { id: 'filter-condition', label: 'Filter condition', required: true }, { id: 'after-unit', label: 'AC unit after service', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ac-gas-refill',
    categoryId: 'ac-repair',
    name: 'AC Gas Refill',
    shortDescription: 'Full gas recharge when cooling performance drops.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fac-gas-refill.jpg',
    basePrice: 149900,
    commissionBps: 2250,
    durationMinutes: 45,
    includes: ['Gas pressure check', 'Top-up to manufacturer spec', 'Leak test post-refill'],
    faq: [{ question: 'How do I know I need a refill?', answer: 'AC cools poorly, takes long to reach target temp, or ice forms on the unit.' }],
    addOns: [],
    photoStages: [{ id: 'pressure-gauge', label: 'Pressure gauge reading before', required: true }, { id: 'after-refill', label: 'Gauge after refill', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'ac-installation',
    categoryId: 'ac-repair',
    name: 'AC Installation',
    shortDescription: 'Professional split AC installation with copper piping.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fac-installation.jpg',
    basePrice: 299900,
    commissionBps: 2000,
    durationMinutes: 180,
    includes: ['Indoor + outdoor unit mounting', 'Copper pipe (up to 3 m)', 'Electrical connection', 'Test run + cooling verification'],
    faq: [{ question: 'Is copper pipe beyond 3m extra?', answer: 'Yes — ₹250/m beyond 3 m.' }],
    addOns: [{ id: 'extra-pipe', name: 'Extra copper pipe', price: 25000, triggerCondition: 'per metre beyond 3 m' }],
    photoStages: [{ id: 'before-wall', label: 'Wall before drilling', required: true }, { id: 'after-install', label: 'Completed installation', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  // Deep Cleaning
  {
    id: 'deep-clean-1bhk',
    categoryId: 'deep-cleaning',
    name: '1 BHK Deep Clean',
    shortDescription: 'Full home deep clean — kitchen, bathroom, living area, bedroom.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fdeep-clean-1bhk.jpg',
    basePrice: 129900,
    commissionBps: 2250,
    durationMinutes: 240,
    includes: ['Kitchen degreasing + scrub', 'Bathroom disinfection', 'Floor mopping + scrubbing', 'Balcony cleaning', 'Window wiping (inside)'],
    faq: [{ question: 'Do I need to clear the home?', answer: 'Remove valuables and breakables. Large furniture can stay.' }],
    addOns: [{ id: 'sofa-clean', name: 'Sofa cleaning (per seat)', price: 39900, triggerCondition: 'add on request' }],
    photoStages: [{ id: 'before-kitchen', label: 'Kitchen before', required: true }, { id: 'after-kitchen', label: 'Kitchen after', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'deep-clean-2bhk',
    categoryId: 'deep-cleaning',
    name: '2 BHK Deep Clean',
    shortDescription: '2 BHK full home deep clean including 2 bathrooms.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fdeep-clean-2bhk.jpg',
    basePrice: 179900,
    commissionBps: 2250,
    durationMinutes: 360,
    includes: ['All rooms + 2 bathrooms', 'Kitchen degreasing', 'Balcony scrub', 'Window wiping (inside)'],
    faq: [{ question: 'How many technicians come?', answer: '2 technicians for a 2 BHK.' }],
    addOns: [{ id: 'mattress-clean', name: 'Mattress cleaning (per mattress)', price: 49900, triggerCondition: 'add on request' }],
    photoStages: [{ id: 'before-bathroom', label: 'Bathroom before', required: true }, { id: 'after-bathroom', label: 'Bathroom after', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'deep-clean-3bhk',
    categoryId: 'deep-cleaning',
    name: '3 BHK Deep Clean',
    shortDescription: '3 BHK full home deep clean — thorough, top-to-bottom.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fdeep-clean-3bhk.jpg',
    basePrice: 229900,
    commissionBps: 2250,
    durationMinutes: 480,
    includes: ['All rooms + 3 bathrooms', 'Kitchen degreasing', 'Balcony scrub x2', 'Window wiping (inside)'],
    faq: [],
    addOns: [],
    photoStages: [{ id: 'before-living', label: 'Living room before', required: true }, { id: 'after-living', label: 'Living room after', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  // Plumbing
  {
    id: 'plumbing-leak-fix',
    categoryId: 'plumbing',
    name: 'Leak Fix',
    shortDescription: 'Stop leaking pipes, taps, or joints — fast.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fplumbing-leak-fix.jpg',
    basePrice: 39900,
    commissionBps: 2250,
    durationMinutes: 60,
    includes: ['Leak location + diagnosis', 'Pipe joint sealing', 'Test after repair'],
    faq: [{ question: 'Are spare parts included?', answer: 'Basic sealant included. Replacement pipe fittings charged at cost.' }],
    addOns: [{ id: 'replacement-fitting', name: 'Replacement fitting', price: 15000, triggerCondition: 'if existing fitting is damaged beyond repair' }],
    photoStages: [{ id: 'leak-location', label: 'Leak point before fix', required: true }, { id: 'after-fix', label: 'After repair', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'plumbing-tap-install',
    categoryId: 'plumbing',
    name: 'Tap / Faucet Installation',
    shortDescription: 'Install or replace any tap or faucet.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fplumbing-tap-install.jpg',
    basePrice: 59900,
    commissionBps: 2250,
    durationMinutes: 45,
    includes: ['Old tap removal', 'New tap fitting + sealing', 'Flow test'],
    faq: [],
    addOns: [],
    photoStages: [{ id: 'before-tap', label: 'Tap before install', required: true }, { id: 'after-tap', label: 'Tap installed', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'plumbing-pipe-repair',
    categoryId: 'plumbing',
    name: 'Pipe Repair',
    shortDescription: 'Cracked or burst pipe repair — wall break-open if needed.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fplumbing-pipe-repair.jpg',
    basePrice: 79900,
    commissionBps: 2250,
    durationMinutes: 90,
    includes: ['Pipe inspection + damage assessment', 'Section replacement', 'Leak test'],
    faq: [{ question: 'Is wall repair included?', answer: 'No — wall plastering is a separate service.' }],
    addOns: [{ id: 'wall-plaster', name: 'Wall patching (per sq ft)', price: 20000, triggerCondition: 'if wall break-open is required' }],
    photoStages: [{ id: 'before-pipe', label: 'Damaged pipe', required: true }, { id: 'after-pipe', label: 'Repaired section', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  // Electrical
  {
    id: 'electrical-fan-install',
    categoryId: 'electrical',
    name: 'Ceiling Fan Installation',
    shortDescription: 'Safe, secure ceiling fan installation by a licensed electrician.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Felectrical-fan-install.jpg',
    basePrice: 29900,
    commissionBps: 2250,
    durationMinutes: 45,
    includes: ['Fan mounting on hook / canopy', 'Wiring to existing point', 'Test run'],
    faq: [{ question: 'Is new wiring included?', answer: 'No — if a new point is needed, that is a separate wiring charge.' }],
    addOns: [],
    photoStages: [{ id: 'before-ceiling', label: 'Ceiling point before', required: false }, { id: 'fan-installed', label: 'Fan installed', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'electrical-switchboard-fix',
    categoryId: 'electrical',
    name: 'Switchboard Repair',
    shortDescription: 'Fix faulty switches, sockets, or MCBs.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Felectrical-switchboard-fix.jpg',
    basePrice: 39900,
    commissionBps: 2250,
    durationMinutes: 60,
    includes: ['Fault diagnosis', 'Switch / socket replacement (up to 3 points)', 'Earthing check'],
    faq: [],
    addOns: [{ id: 'extra-point', name: 'Extra point repair', price: 10000, triggerCondition: 'per point beyond 3' }],
    photoStages: [{ id: 'faulty-board', label: 'Faulty switchboard', required: true }, { id: 'repaired-board', label: 'After repair', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'electrical-wiring',
    categoryId: 'electrical',
    name: 'New Point Wiring',
    shortDescription: 'Add a new electrical point — socket, switch, or light.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Felectrical-wiring.jpg',
    basePrice: 99900,
    commissionBps: 2250,
    durationMinutes: 120,
    includes: ['Conduit + wiring (up to 5 m)', 'New socket / switch fitting', 'MCB protection check'],
    faq: [{ question: 'Is concealed wiring possible?', answer: 'Yes — wall chasing + plastering is an add-on.' }],
    addOns: [{ id: 'wall-chasing', name: 'Wall chasing + plaster', price: 30000, triggerCondition: 'per metre of concealed wiring' }],
    photoStages: [{ id: 'before-wall', label: 'Wall before wiring', required: false }, { id: 'completed-point', label: 'New point completed', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  // Pest Control
  {
    id: 'pest-cockroach',
    categoryId: 'pest-control',
    name: 'Cockroach Control',
    shortDescription: 'Gel treatment for complete cockroach elimination.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fpest-cockroach.jpg',
    basePrice: 59900,
    commissionBps: 2250,
    durationMinutes: 60,
    includes: ['Gel bait application at all infestation points', '30-day re-treatment guarantee', 'Safe for children + pets'],
    faq: [{ question: 'When can I use the kitchen after treatment?', answer: '30 minutes — gel is odourless and surface-safe.' }],
    addOns: [],
    photoStages: [{ id: 'infestation-spots', label: 'Key infestation areas', required: false }, { id: 'post-treatment', label: 'Gel application', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pest-bed-bugs',
    categoryId: 'pest-control',
    name: 'Bed Bug Treatment',
    shortDescription: 'Heat + chemical treatment for full bed bug elimination.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fpest-bed-bugs.jpg',
    basePrice: 149900,
    commissionBps: 2250,
    durationMinutes: 120,
    includes: ['Mattress + furniture inspection', 'Residual spray treatment', '60-day guarantee', 'Follow-up visit if reinfestation'],
    faq: [{ question: 'How soon can I sleep on the bed?', answer: 'After 4 hours once the spray dries.' }],
    addOns: [],
    photoStages: [{ id: 'mattress-before', label: 'Mattress before treatment', required: true }, { id: 'after-treatment', label: 'Post-treatment', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: 'pest-full-home',
    categoryId: 'pest-control',
    name: 'Full Home Pest Control',
    shortDescription: 'Comprehensive treatment for all common household pests.',
    heroImageUrl: 'https://firebasestorage.googleapis.com/v0/b/homeservices-mvp/o/services%2Fpest-full-home.jpg',
    basePrice: 249900,
    commissionBps: 2250,
    durationMinutes: 180,
    includes: ['Cockroaches, ants, lizards, silverfish, spiders', 'Spray + gel combo', 'All rooms + kitchen + bathrooms', '90-day guarantee'],
    faq: [{ question: 'Is it safe for pets?', answer: 'Pets should be removed during treatment and for 2 hours after.' }],
    addOns: [{ id: 'mosquito-fogging', name: 'Mosquito fogging (outdoor)', price: 49900, triggerCondition: 'if outdoor space > 500 sq ft' }],
    photoStages: [{ id: 'before-overview', label: 'Home overview before', required: false }, { id: 'treatment-in-progress', label: 'Treatment in progress', required: true }],
    isActive: true,
    updatedBy: SYSTEM,
    createdAt: NOW,
    updatedAt: NOW,
  },
];

async function seed(): Promise<void> {
  const db = getCosmosClient().database(DB_NAME);

  // Ensure containers exist (idempotent)
  await db.containers.createIfNotExists({ id: 'service_categories', partitionKey: '/id', defaultTtl: -1 });
  await db.containers.createIfNotExists({ id: 'services', partitionKey: '/categoryId' });

  const catContainer = db.container('service_categories');
  const svcContainer = db.container('services');

  console.log('Seeding service_categories...');
  for (const cat of CATEGORIES) {
    await catContainer.items.upsert(cat);
    console.log(`  upserted: ${cat.id}`);
  }

  console.log('Seeding services...');
  for (const svc of SERVICES) {
    await svcContainer.items.upsert(svc);
    console.log(`  upserted: ${svc.id}`);
  }

  console.log(`Done. ${CATEGORIES.length} categories, ${SERVICES.length} services.`);
}

seed().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
